Abramov Ivan. Shell (HW №1)
AirVan21/Software-Design pull request #1
Opened 2016-10-04 23:30 UTC by AirVan21

@yurii-litvinov, please, take a look

UML (class diagram) will be soon.

2016-10-17 16:08 UTC, yurii-litvinov requested changes
- набираю x=1, падает с Exception in thread "main" ru.spbau.shell.exceptions.WrongCommandException: Wrong command!, причём даже выходит из программы
- набираю 
  x = 1
  echo $x
  --- получаю "x", внезапно
- набираю x = echo
  --- получаю "окт 17, 2016 6:32:51 PM ru.spbau.shell.utility.GlobalLogger log
  INFO: Command not found!"
  При этом все тесты проходят :)

В общем, архитектура мне нравится, написано аккуратно, но не работает. Надо поправить или рассказать мне, что я делаю не так.

2016-10-17 16:08 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/environment/Environment.java
> +        return  result != null ? Optional.of(result) : Optional.empty();
Лишний пробел после return :)

2016-10-17 16:08 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/utility/FileManager.java
> +    public static Set<String> listFiles(String path, boolean isRecursive) {
Нужен комментарий.

2016-10-17 16:08 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/visitors/ShellVisitor.java
> +
А тут лишняя пустая строчка :) Я ещё выше видел, но лень отмечать.

2016-10-17 16:08 UTC, yurii-litvinov commented on Commands/src/test/java/ru/spbau/shell/ShellTest.java
> +    }
Хороший тест :)^U

2016-10-17 16:08 UTC, yurii-litvinov commented on README.md
> +![UML Class Diagram](https://raw.githubusercontent.com/AirVan21/Software-Design/shell/Commands/diagram/ClassDiagram.png)
Что-то в коде существенно больше классов, как мне показалось, чем на диаграмме.

2016-10-18 10:32 UTC, AirVan21 commented on README.md
> +![UML Class Diagram](https://raw.githubusercontent.com/AirVan21/Software-Design/shell/Commands/diagram/ClassDiagram.png)
Я подумал, что нужно описать основную логику, которую реализовывал я.
Те классы, которые генерировал ANTLR я не включал в таблицу. Мне нужна была диаграмма классов, которая хорошо подходит под краткое описание, которое я сделал в README.

2016-10-18 10:48 UTC, AirVan21 commented on Commands/src/test/java/ru/spbau/shell/ShellTest.java
> +    }
Спасибо :100:

2016-10-24 22:35 UTC, AirVan21 commented on Commands/src/main/java/ru/spbau/shell/environment/Environment.java
> +        return  result != null ? Optional.of(result) : Optional.empty();
Чего-то нет (

2016-11-02 12:15 UTC, yurii-litvinov approved these changes
Для прототипа пойдёт, зачтена

2016-11-02 12:15 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/visitors/ExitVisitor.java
> +
Лишняя пустая строка :)

2016-11-02 12:15 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/visitors/GrepVisitor.java
> +    /**
А тут наоборот, пустой строки не хватает.

2016-11-02 12:15 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/visitors/PipeVisitor.java
> + */
Комментарий не оч

2016-11-02 12:15 UTC, yurii-litvinov commented on Commands/src/main/java/ru/spbau/shell/visitors/ShellVisitor.java
> +     * @param ctx - context for specific command
Дефисы не надо, а то после генерации JavaDoc-а они будут страшно выглядеть.

2016-11-02 12:15 UTC, merged